# Generated by Django 2.0b1 on 2017-11-10 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171110_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('chirperuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ChirperUser')),
            ],
        ),
    ]
