# Generated by Django 2.0b1 on 2017-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='chirping_at',
            field=models.ManyToManyField(related_name='chirping_at_set', to='app.ChirperUser'),
        ),
    ]
